### ISSUE TITLE
Unable to login - uninitialized constant ApiEnv::FILE_PATH

### ISSUE THREAD

**Issue by tommyvernieri** [wesabe/pfc#13]
After importing my snapshot, I can't login. I provide my username and the temporary "changeme!" password on the login screen and the resulting page has the error message below. The URL stays as http://mesabeubuntu:3000/login

```
NameError in SessionsController#create

uninitialized constant ApiEnv::FILE_PATH

Rails.root: /home/mesabeadmin/wesabe/pfc
Application Trace | Framework Trace | Full Trace

app/controllers/application_controller.rb:21:in `ssu_enabled?'
app/models/user/account_update_manager.rb:37:in `ssu_enabled?'
app/models/user/account_update_manager.rb:19:in `login!'
app/models/user/account_update_manager.rb:41:in `login!'
app/models/user.rb:263:in `after_login'
app/controllers/sessions_controller.rb:41:in `create'
```

**Comment by tommyvernieri** [comment]
I think this was happening because I pulled the latest pfc source without restarting the pfc server process.

**Comment by eventualbuddha** [comment]
Sounds right. Is it working for you now?

**Comment by tommyvernieri** [comment]
Yep got it working again. User error.
