### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by epall** [wesabe/pfc#36]
When trying to import my snapshot from Wesabe into Mesabe, I get the following error

<pre>
/Users/epall/wesabe/pfc/lib/importer/wesabe.rb:421:in `associate_transfers': You have a nil object when you didn't expect it! (NoMethodError)
You might have expected an instance of ActiveRecord::Base.
The error occurred while evaluating nil.[]
    from /Users/epall/wesabe/pfc/lib/importer/wesabe.rb:414:in `each'
    from /Users/epall/wesabe/pfc/lib/importer/wesabe.rb:414:in `associate_transfers'
    from /Users/epall/wesabe/pfc/lib/importer/wesabe.rb:73:in `import'
    from /Users/epall/wesabe/pfc/lib/importer/wesabe.rb:12:in `import'
    from /Users/epall/wesabe/pfc/lib/tasks/snapshot.thor:7:in `import'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/task.rb:22:in `send'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/task.rb:22:in `run'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/invocation.rb:109:in `invoke'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/invocation.rb:116:in `call'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/invocation.rb:116:in `invoke'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor.rb:161:in `start'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/base.rb:379:in `start'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor.rb:140:in `start'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/runner.rb:34:in `method_missing'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/task.rb:22:in `send'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/task.rb:22:in `run'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/task.rb:108:in `run'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/invocation.rb:109:in `invoke'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/invocation.rb:116:in `call'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/invocation.rb:116:in `invoke'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor.rb:161:in `start'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor/base.rb:379:in `start'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/lib/thor.rb:140:in `start'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/gems/thor-0.13.8/bin/thor:6
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/bin/thor:19:in `load'
    from /Users/epall/.rvm/gems/ruby-1.8.7-p302@mesabe/bin/thor:19
</pre>

I wonder if this is due to a buggy transaction I created while developing transfers...

**Comment by epall** [comment]
Whoops, looks like I was using a really old version of pfc
