### ISSUE TITLE
Downloaded snapshot cannot be imported if it is re-zipped

### ISSUE THREAD

**Issue by eventualbuddha** [wesabe/pfc#4]
_This issue is for historical purposes - which is why the language is a bit funny - it didn't actually happen to me._

Downloading a snapshot in Safari on Mac OS X will unzip the snapshot file and discard the original zip file, but `pfc` requires a zip file to import for snapshots. So one might re-zip the folder that Finder created to contain the unzipped files, but that zip file doesn't work for importing. One might get a stack trace that looks like this:

```
$ thor snapshot:import ~/Desktop/brian-donovan.zip -v
unzipping snapshot...
importing user...
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/pathname.rb:749:in `read': No such file or directory - /var/folders/Bo/BoDYGSa6HmCzsonS1I0U5E+++TI/-Tmp-/tempfilepath20100726-27646-t0qlkp-0/user.json (Errno::ENOENT)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/pathname.rb:749:in `read'
    from /Users/marc/mesabe/pfc/lib/importer/wesabe.rb:33:in `import'
    from /Users/marc/mesabe/pfc/lib/importer/wesabe.rb:12:in `import'
    from /Users/marc/mesabe/pfc/lib/tasks/snapshot.thor:10:in `import'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/task.rb:22:in `send'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/task.rb:22:in `run'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/invocation.rb:118:in `invoke_task'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor.rb:246:in `dispatch'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/base.rb:389:in `start'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/runner.rb:34:in `method_missing'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/task.rb:22:in `send'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/task.rb:22:in `run'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/task.rb:108:in `run'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/invocation.rb:118:in `invoke_task'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor.rb:246:in `dispatch'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/lib/thor/base.rb:389:in `start'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.0/bin/thor:6
    from /usr/bin/thor:19:in `load'
    from /usr/bin/thor:19
```

**Comment by eventualbuddha** [comment]
Account for rezipped snapshots. Closed by 940a39e15ec57baa3c4d37ace6cf9f5b2b1126fc.
