### ISSUE TITLE
Loading charts fails

### ISSUE THREAD

**Issue by nylen** [wesabe/pfc#5]
On my installation, the charts on the main page fail to load since app/views/profiles/show.xml.builder still contains a reference to User#cached_country, which was removed by 919f4eddca4278f2c23e3cf7cb4ddbbeef2d94ef.  Here is a stack trace:

```
ActionView::Template::Error (undefined method `cached_country' for #<User:0xaf9f8c9c>):
    5:   if @user == current_user
    6:     xml.username(@user.username)
    7:     xml.postal_code(@user.postal_code)
    8:     xml.country(@user.cached_country.name, :id => @user.country_id) if @user.country_id
    9:     xml.email(@user.email)
    10:     xml.default_currency(@user.default_currency.name,
    11:         :separator => @user.default_currency.separator,
/usr/lib/ruby/gems/1.8/gems/activemodel-3.0.0.beta4/lib/active_model/attribute_methods.rb:358:in `method_missing'
  /usr/lib/ruby/gems/1.8/gems/activerecord-3.0.0.beta4/lib/active_record/attribute_methods.rb:45:in `method_missing'
  /opt/wesabe/pfc/app/views/profiles/show.xml.builder:8:in `_render_template__1009861017__671239938_0'
  /usr/lib/ruby/gems/1.8/gems/builder-2.1.2/lib/builder/xmlbase.rb:134:in `call'
  /usr/lib/ruby/gems/1.8/gems/builder-2.1.2/lib/builder/xmlbase.rb:134:in `_nested_structures'
  /usr/lib/ruby/gems/1.8/gems/builder-2.1.2/lib/builder/xmlbase.rb:58:in `method_missing'
  /opt/wesabe/pfc/app/views/profiles/show.xml.builder:3:in `_render_template__1009861017__671239938_0'
  /usr/lib/ruby/gems/1.8/gems/actionpack-3.0.0.beta4/lib/action_view/template.rb:134:in `send'
  /usr/lib/ruby/gems/1.8/gems/actionpack-3.0.0.beta4/lib/action_view/template.rb:134:in `render'
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.0.0.beta4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.0.0.beta4/lib/active_support/notifications.rb:48:in `__send__'
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.0.0.beta4/lib/active_support/notifications.rb:48:in `instrument'
  /usr/lib/ruby/gems/1.8/gems/actionpack-3.0.0.beta4/lib/action_view/template.rb:126:in `render'
  /usr/lib/ruby/gems/1.8/gems/actionpack-3.0.0.beta4/lib/action_view/render/rendering.rb:58:in `_render_template'
  [...]
```

Reinstating User#cached_country worked for me: nylen@7b8ccff86b4d0b49a7ffaed9c5490aa69329f97a

**Comment by eventualbuddha** [comment]
Fixed by fd94660200812278776b2457b62f8b8b7d748057.
